### ISSUE TITLE
How to tell if whosatmyfeeder is working?

### ISSUE THREAD

**Issue by hermy65** [mmcc-xx/WhosAtMyFeeder#18]
New to all of these software packages. I installed both Frigate and WhosAtMyFeeder on my unraid box. Frigate appears to be detecting what is needed, only had one detection of a bird and it was actually a squirrel. The issue im potentially running into is, how do i know if this is actually working. When Frigate classified the squirrel as a bird, it never showed up in WhosAtMyFeeder even though it was incorrect, i also did not see anything in the logs for WhosAtMyFeeder to suggest it decided against the squirrel. 

So, how do i know this is working?

Below is my frigate config

`mqtt:
  host: 192.168.0.134
  port: 1883
  topic_prefix: frigate
  user: user
  password: pass
  stats_interval: 60
detectors:
  tensorrt:
    type: tensorrt
    device: 0
model:
  path: /trt-models/yolov7-tiny-416.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 416
  height: 416
ffmpeg:
  global_args: -hide_banner -loglevel warning
  hwaccel_args: preset-nvidia-h264
  input_args: preset-rtsp-generic
  output_args:
    # Optional: output args for detect streams (default: shown below)
    detect: -threads 2 -f rawvideo -pix_fmt yuv420p
    # Optional: output args for record streams (default: shown below)
    record: preset-record-generic
detect:
  width: 1920
  height: 1080
  enabled: true
objects:
  track:
    - bird
    - dog
    - person
  filters:
    bird:
      threshold: 0.6
      min_area: 5000
snapshots:
  enabled: true
cameras:
  birdcam:
    record:
        enabled: True
        events:
          pre_capture: 5
          post_capture: 5
          objects:
            - bird
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://192.168.0.199:8554/cam
          roles:
            - detect
            - record
    live:
      stream_name: birdcam
    mqtt:
      enabled: True
      bounding_box: False #this will get rid of the box around the bird. We already know it is a bird. Sheesh.
      timestamp: False #this will get rid of the time stamp in the image. 
      quality: 95 #default quality is 70, which will get you lots of compression artifacts
`

**Comment by stevenbrown1862** [comment]
Not really an expert but one way which may work would be to temporarily lower the confidence needed in frigate and this app and then hopefully you should see some random garden objects getting named as random birds.
An other way if you have any video of birds, then you could feed this video as a camera stream using go2rtc.
I've been using this second method to fine tune my pond heron detection.

**Comment by hermy65** [comment]
> Not really an expert but one way which may work would be to temporarily lower the confidence needed in frigate and this app and then hopefully you should see some random garden objects getting named as random birds. An other way if you have any video of birds, then you could feed this video as a camera stream using go2rtc. I've been using this second method to fine tune my pond heron detection.

@stevenbrown1862 Still grasping Frigate as a whole, how would i go about feeding a video into it using go2rtc?

**Comment by stevenbrown1862** [comment]
I don't know how you have frigate set up currently. But adding something like the following to your streams section in the frigate config.   You'll have to make sure that you've mounted the whole config folder, I think sometimes people only mount the config file. 

streams:
  birdvideo: ffmpeg:/config/my video.mp4

You will then have this video looping at rtsp://frigate ip:8554/birdvideo and so you can point a frigate camera to it. 


Sorry for any typos but tricky to type on the phone.

**Comment by hermy65** [comment]
> I don't know how you have frigate set up currently. But adding something like the following to your streams section in the frigate config. You'll have to make sure that you've mounted the whole config folder, I think sometimes people only mount the config file.
> 
> streams: birdvideo: ffmpeg:/config/my video.mp4
> 
> You will then have this video looping at rtsp://frigate ip:8554/birdvideo and so you can point a frigate camera to it.
> 
> Sorry for any typos but tricky to type on the phone.

definitely dont understand frigate well enough to make this work unfortunately. When i add in what you listed above with correct spacing frigate doesnt work. Looked at the documentation and didnt find anything similar to what you had up there either

**Comment by stevenbrown1862** [comment]
If its not working then I think the most likely cause will be that you haven't mapped the config folder into your container.   Sorry I've no idea about unraid so I've no idea how that would work.   This link below is the documentation for streaming an mp4 file. 

https://github.com/AlexxIT/go2rtc#source-ffmpeg

**Comment by hermy65** [comment]
@stevenbrown1862  ok i finally got a video of birds streaming over rtsp and into a new camera in frigate. Now though, its not detecting them as birds at all, more so detecting them as people or not at all??

![image](https://github.com/mmcc-xx/WhosAtMyFeeder/assets/321989/ab7a55d2-7714-4dad-9a87-a16b05c4f5d8)
![image](https://github.com/mmcc-xx/WhosAtMyFeeder/assets/321989/79e0ea85-dfce-4b36-a564-50bb11e01d61)

Below is my frigate config, maybe i have something set incorrectly there? Appreciate the insight!!!

```
mqtt:
  host: 192.168.0.134
  port: 1883
  topic_prefix: frigate
  user: hassmqtt
  password: b4dgersn4ke
  stats_interval: 60
detectors:
  tensorrt:
    type: tensorrt
    device: 0
model:
  path: /trt-models/yolov7-tiny-416.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 416
  height: 416
ffmpeg:
  global_args: -hide_banner -loglevel warning
  hwaccel_args: preset-nvidia-h264
  input_args: preset-rtsp-generic
  output_args:
    # Optional: output args for detect streams (default: shown below)
    detect: -threads 2 -f rawvideo -pix_fmt yuv420p
    # Optional: output args for record streams (default: shown below)
    record: preset-record-generic
detect:
  width: 1920
  height: 1080
  enabled: true
objects:
  track:
    - bird
    - dog
    - person
  filters:
    bird:
      threshold: 0.4
      min_area: 5000
snapshots:
  enabled: true
cameras:
  birdcam:
    record:
        enabled: True
        events:
          pre_capture: 5
          post_capture: 5
          objects:
            - bird
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://192.168.0.199:8554/cam
          roles:
            - detect
            - record
  birdtest:
    record:
        enabled: True
        events:
          pre_capture: 5
          post_capture: 5
          objects:
            - bird
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://192.168.0.115:8554/live
          roles:
            - detect
            - record
    live:
      stream_name: birdcam
    mqtt:
      enabled: True
      bounding_box: False #this will get rid of the box around the bird. We already know it is a bird. Sheesh.
      timestamp: False #this will get rid of the time stamp in the image. 
      quality: 95 #default quality is 70, which will get you lots of compression artifacts
```
