### ISSUE TITLE
MQTT Connected | Unexpected disconnection, trying to reconnect

### ISSUE THREAD

**Issue by hs82h** [mmcc-xx/WhosAtMyFeeder#29]
Frigate is running fine without any errors, but WhosAtMyFeeder gives me te following error messages in the logs:

```
MQTT Connected
Unexpected disconnection, trying to reconnect
```

My config is as follows:

```
frigate:
  frigate_url: http://u2.lan:5000
  mqtt_server: u1.lan
  mqtt_auth: false
  mqtt_username: mosquitto
  mqtt_password: *******************
  main_topic: frigate
  camera:
    - d2ep
    - fi9900p
  object: bird
classification:
  model: model.tflite
  threshold: 0.7
webui:
  port: 7766
  host: 0.0.0.0
```

How can I troubleshoot this?
