### ISSUE TITLE
Frigation detection tips

### ISSUE THREAD

**Issue by poxin13** [mmcc-xx/WhosAtMyFeeder#8]
Any tips on how to get frigate to detect birds better? I've got a 4k camera and have tried various angles, settings, etc but it seems to only pick them up "sometimes" even with what I would consider a very clear and dead-on view on the bird. Love the app by the way this is super cool.

**Comment by mmcc-xx** [comment]
I'm glad you are enjoying it!

Below is part of my frigate config file. Note especially...

```
      filters:
        bird:
          threshold: 0.6
          min_area: 5000
```

If you dial down threshold you'll get more detections, but more of them will be false positives. Most of the false positives will be filtered out by WhosAtMyFeeder. Default is 0.7

min_area is by default 0, so setting this to some value greater than 5000 will make sure it isn't flagging tiny little dots as birds.

Also note that in the width and height section under detect I'm feeding the model full sized frames. This requires more processing but should (I think) work better.

```
  birdcam:
    ffmpeg:
      input_args: preset-rtmp-generic
      inputs:
        - path: rtmp://192.168.1.114/bcs/channel0_main.bcs?channel=0&stream=0&user=admin&password=password
          roles:
            - detect
            - record
      output_args:
        record: preset-record-generic-audio-copy
      hwaccel_args: preset-vaapi
    live:
      stream_name: birdcam
    detect:
      enabled: True
      width: 2560
      height: 1920
      fps: 6
    record:
      enabled: true
    snapshots:
      enabled: true
    mqtt:
      bounding_box: False
      timestamp: False
      quality: 95
    objects:
      track:
        - bird
      filters:
        bird:
          threshold: 0.6
          min_area: 5000
```
